name: Lambda Scale Down Runners
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/lambda-scale-down.yml
      - "modules/runners/lambdas/scale-down/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:12
    defaults:
      run:
        working-directory: modules/runners/lambdas/scale-down

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build distribution
        run: yarn build
